### ISSUE TITLE
请理智反习（非粉红）

### ISSUE THREAD

**Issue by Chastinian** [AntiXJP/HealthCode#4]
您好，希望您在维护此项目时三思：这个项目容易破坏抗疫工作，导致大规模感染（苹果和谷歌在去年就在效仿健康码制度了）。虽然共产党专制，但是不代表共产党所有的政策全是错误的，中国实行侵犯自由的防疫制度反倒控制了疫情蔓延。所以我认为，做一个对抗网络审查的项目比这个项目好得多。如果您觉得健康码不好，欢迎与我理智交换观点，谢谢。

**Comment by Chastinian** [comment]
补充：如果作者是支黑想让全中国人都感染新冠而死，那么我们无话可说。想屠支，请先从您自己开始。

**Comment by EDTmagiclab** [comment]
你好，我是来拉大便的，请问有手纸吗？嗯，这堆代码挺合适啊
