### ISSUE TITLE
作者的版本和原作者最后1.6.0版仍有一些区别

### ISSUE THREAD

**Issue by sagerlikesspring** [AntiXJP/HealthCode#9]
原作者1.6.0版修复了在系统英文下显示不出特定地区健康码的bug，具体可以在我的仓库中找到我之前备份的版本

顺便一提，issues一堆粉蛆和迫真理科中，一突开，溅得我满脸喷粪啊。一片好心的作者被爱举报的蜘蛛吓得立即自己下架了，没想到它们很爱自己的良民证，有较强的自我阉割意识。建议作者学习fuck-xuexiqiangguo作者加强硬度，直接将反极权反洗脑的pin在顶端，毕竟恶习及其杂犬像弹簧，你弱它就强。

**Comment by sagerlikesspring** [comment]
看到圈内台阶们来自由世界喷粪，我手中的🕷切按耐不住：
简单对等回击一下
![1ramxdjiqx961](https://user-images.githubusercontent.com/77372972/104412452-30474600-5564-11eb-80d3-a52146684a15.jpg)

当然，太多的还是直接删帖控平罢了，顺便放上开智脑白金。要治理nmslese污染还是要两手都要抓，两手都要硬

**Comment by AntiXJP** [comment]
> 原作者1.6.0版修复了在系统英文下显示不出特定地区健康码的bug，具体可以在我的仓库中找到我之前备份的版本


肥肠感谢，我昨天没处理英文的
